var searchData=
[
  ['acquirechannel',['acquireChannel',['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManager.html#ab7993d1288712d7e23fd277de593765a',1,'multiAgentExperience::library::activity::FocusManager::acquireChannel(const std::string &amp;channelName, std::shared_ptr&lt; ChannelObserverInterface &gt; channelObserver, const std::string &amp;interfaceName) override'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManager.html#a7db083bf9d1878ce6a0a7d5b22379c3a',1,'multiAgentExperience::library::activity::FocusManager::acquireChannel(const std::string &amp;channelName, std::shared_ptr&lt; FocusManagerInterface::Activity &gt; channelActivity) override'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManagerInterface.html#ae313e8edeeb2301a93509aea84ea06f4',1,'multiAgentExperience::library::activity::FocusManagerInterface::acquireChannel(const std::string &amp;channelName, std::shared_ptr&lt; ChannelObserverInterface &gt; channelObserver, const std::string &amp;interfaceName)=0'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManagerInterface.html#aaa59dc1dd0b5e82f85957b42acdb9129',1,'multiAgentExperience::library::activity::FocusManagerInterface::acquireChannel(const std::string &amp;channelName, std::shared_ptr&lt; FocusManagerInterface::Activity &gt; channelActivity)=0']]],
  ['activityrequestinterface',['ActivityRequestInterface',['../../../../output/max-library/html/classmultiAgentExperience_1_1activity_1_1ActivityRequestInterface.html#ab47c71634e6c6e151dab14e8940cc14e',1,'multiAgentExperience::activity::ActivityRequestInterface']]],
  ['addobserver',['addObserver',['../../../../output/max-library/html/classmultiAgentExperience_1_1control_1_1ControlManagerInterface.html#a1eecd64ef0a532d53982db500c9c3e14',1,'multiAgentExperience::control::ControlManagerInterface::addObserver()'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1core_1_1transformer_1_1ControlManagerTransformer.html#ae8411949b927e79efe6f079bb87ff6c7',1,'multiAgentExperience::library::core::transformer::ControlManagerTransformer::addObserver()'],['../../../../output/max-library/html/classmultiAgentExperience_1_1utils_1_1data_1_1DataWriterInterface.html#a9560ec91c573d7e565337c245b581e11',1,'multiAgentExperience::utils::data::DataWriterInterface::addObserver()'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1experience_1_1ExperienceManager.html#a79e1702ae84014ce72e428cba8a9f169',1,'multiAgentExperience::library::experience::ExperienceManager::addObserver(std::weak_ptr&lt; multiAgentExperience::experience::ExperienceObserverInterface &gt; observer) override'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1experience_1_1ExperienceManager.html#a79e1702ae84014ce72e428cba8a9f169',1,'multiAgentExperience::library::experience::ExperienceManager::addObserver(std::weak_ptr&lt; multiAgentExperience::experience::ExperienceObserverInterface &gt; observer) override'],['../../../../output/max-library/html/classmultiAgentExperience_1_1experience_1_1ExperienceManagerInterface.html#a91511d0763219024ffd6d07befbb5b71',1,'multiAgentExperience::experience::ExperienceManagerInterface::addObserver()'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManager.html#acfed58847fed26dd1c3127c84f69e15b',1,'multiAgentExperience::library::activity::FocusManager::addObserver()'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManagerInterface.html#a7a94ace92453137b6b0011593d81b2f8',1,'multiAgentExperience::library::activity::FocusManagerInterface::addObserver()']]],
  ['addrenderer',['addRenderer',['../classmultiAgentExperience_1_1sampleApplication_1_1experienceManager_1_1ExperienceManager.html#a7c4373c77e4989ae73432721e70d3f6e',1,'multiAgentExperience::sampleApplication::experienceManager::ExperienceManager::addRenderer()'],['../classmultiAgentExperience_1_1sampleApplication_1_1universalDeviceCommandManager_1_1UniversalDeviceCommandManager.html#aed2b7a10f9781b8d2bc55301784f0cbc',1,'multiAgentExperience::sampleApplication::universalDeviceCommandManager::UniversalDeviceCommandManager::addRenderer()']]],
  ['agent',['Agent',['../../../../output/max-library/html/classmultiAgentExperience_1_1agent_1_1Agent.html#a6556439e5fced10466a46d4b0afb1d11',1,'multiAgentExperience::agent::Agent']]],
  ['agentsummary',['AgentSummary',['../structmultiAgentExperience_1_1sampleApplication_1_1agentManager_1_1AgentManager_1_1AgentSummary.html#a3229b9c7090c6933cf265bea2ca2c636',1,'multiAgentExperience::sampleApplication::agentManager::AgentManager::AgentSummary']]],
  ['animationengine',['AnimationEngine',['../classmultiAgentExperience_1_1sampleApplication_1_1experienceManager_1_1senseHat_1_1ledController_1_1AnimationEngine.html#a678d9b347f09597c8a758eba4eb0f1df',1,'multiAgentExperience::sampleApplication::experienceManager::senseHat::ledController::AnimationEngine']]],
  ['applicationconfig',['ApplicationConfig',['../structmultiAgentExperience_1_1sampleApplication_1_1ApplicationConfig.html#a77c8d8f0356bd94245184aac9c07f6cd',1,'multiAgentExperience::sampleApplication::ApplicationConfig']]],
  ['applyfrontend',['ApplyFrontend',['../classmultiAgentExperience_1_1sampleApplication_1_1audioManager_1_1wakeword_1_1kittai_1_1SnowboyWrapper.html#a9adafd4fd6552d420e46dd7341e6ee17',1,'multiAgentExperience::sampleApplication::audioManager::wakeword::kittai::SnowboyWrapper']]],
  ['audioformat',['AudioFormat',['../../../../output/max-library/html/structmultiAgentExperience_1_1audio_1_1AudioFormat.html#a12e8c7399c651aa16618d4f688289825',1,'multiAgentExperience::audio::AudioFormat::AudioFormat()'],['../../../../output/max-library/html/structmultiAgentExperience_1_1audio_1_1AudioFormat.html#a51a832f8736e76bc0a32aaca0d55859f',1,'multiAgentExperience::audio::AudioFormat::AudioFormat(std::size_t sampleRateHz, std::size_t numChannels, std::size_t wordsPerSample, std::size_t wordSizeBits=CHAR_BIT, Encoding encoding=Encoding::LPCM, Endianness endianness=Endianness::LITTLE)']]],
  ['avssdk_5fkwdadapterkeywordobserver',['AVSSDK_KWDAdapterKeywordObserver',['../classmultiAgentExperience_1_1sampleApplication_1_1audioManager_1_1wakeword_1_1avssdk_1_1AVSSDK__KWDAdapterKeywordObserver.html#acb0c90265e8390746c94d2352275901f',1,'multiAgentExperience::sampleApplication::audioManager::wakeword::avssdk::AVSSDK_KWDAdapterKeywordObserver']]]
];
