var searchData=
[
  ['name',['name',['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManager_1_1ChannelConfiguration.html#a18e13cb4aad41d39fe5cb3fbd3b06cad',1,'multiAgentExperience::library::activity::FocusManager::ChannelConfiguration::name()'],['../../../../output/sample-application/html/structmultiAgentExperience_1_1sampleApplication_1_1agentManager_1_1AgentsConfig_1_1AgentConfig.html#a70a56495e7acd85084760b7fdfb28936',1,'multiAgentExperience::sampleApplication::agentManager::AgentsConfig::AgentConfig::name()'],['../../../../output/sample-application/html/structmultiAgentExperience_1_1sampleApplication_1_1audioManager_1_1wakeword_1_1WakewordEnginesConfig_1_1EngineConfig.html#a9a3873456cbdbc346cda4ed85dbb535e',1,'multiAgentExperience::sampleApplication::audioManager::wakeword::WakewordEnginesConfig::EngineConfig::name()']]],
  ['noncopyable',['NonCopyable',['../../../../output/sample-application/html/classmultiAgentExperience_1_1sampleApplication_1_1experienceManager_1_1senseHat_1_1ledController_1_1NonCopyable.html',1,'multiAgentExperience::sampleApplication::experienceManager::senseHat::ledController']]],
  ['noopcblauthrequester',['NoopCBLAuthRequester',['../../../../output/sample-application/html/classmultiAgentExperience_1_1sampleApplication_1_1agentManager_1_1alexa_1_1NoopCBLAuthRequester.html',1,'multiAgentExperience::sampleApplication::agentManager::alexa']]],
  ['notifyobserver',['notifyObserver',['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1FocusManagerInterface_1_1Activity.html#ad8728af41101e12f9c29923ed0d79c15',1,'multiAgentExperience::library::activity::FocusManagerInterface::Activity']]],
  ['notifyofactivityupdates',['notifyOfActivityUpdates',['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1ActivityTrackerInterface.html#a639acb228e45d3b8f7311be3bc08a22c',1,'multiAgentExperience::library::activity::ActivityTrackerInterface::notifyOfActivityUpdates()'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1LoggingActivityTracker.html#aebc2a533e045da2b789e348877cf0ce4',1,'multiAgentExperience::library::activity::LoggingActivityTracker::notifyOfActivityUpdates(const std::vector&lt; Channel::State &gt; &amp;channelStates) override'],['../../../../output/max-library/html/classmultiAgentExperience_1_1library_1_1activity_1_1LoggingActivityTracker.html#aebc2a533e045da2b789e348877cf0ce4',1,'multiAgentExperience::library::activity::LoggingActivityTracker::notifyOfActivityUpdates(const std::vector&lt; Channel::State &gt; &amp;channelStates) override']]],
  ['numchannels',['NumChannels',['../../../../output/sample-application/html/classmultiAgentExperience_1_1sampleApplication_1_1audioManager_1_1wakeword_1_1kittai_1_1SnowboyWrapper.html#ac5aa863bc020a3b226317760a1e13155',1,'multiAgentExperience::sampleApplication::audioManager::wakeword::kittai::SnowboyWrapper::NumChannels()'],['../../../../output/max-library/html/structmultiAgentExperience_1_1audio_1_1AudioFormat.html#a4865eb66cb54fc9ade1656ab2702f6f2',1,'multiAgentExperience::audio::AudioFormat::numChannels()']]]
];
